package com.community.model.base;

import java.io.Serializable;
import java.util.Date;

public class Token implements Serializable {
    private String tokenId;
    private String userId;
    private Date tokenCreateTime;
    private Date tokenUpdateTime;
    private Date tokenExpireTime;
    private String cur_club_id;
    private static final long serialVersionUID = 1L;

    public String getTokenId() {
        return tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId == null ? null : tokenId.trim();
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    public Date getTokenCreateTime() {
        return tokenCreateTime;
    }

    public void setTokenCreateTime(Date tokenCreateTime) {
        this.tokenCreateTime = tokenCreateTime;
    }

    public Date getTokenUpdateTime() {
        return tokenUpdateTime;
    }

    public void setTokenUpdateTime(Date tokenUpdateTime) {
        this.tokenUpdateTime = tokenUpdateTime;
    }

    public Date getTokenExpireTime() {
        return tokenExpireTime;
    }

    public void setTokenExpireTime(Date tokenExpireTime) {
        this.tokenExpireTime = tokenExpireTime;
    }

    public String getCur_club_id() {
        return cur_club_id;
    }

    public void setCur_club_id(String cur_club_id) {
        this.cur_club_id = cur_club_id;
    }

    @Override
    public String toString() {
        return "Token{" +
                "tokenId='" + tokenId + '\'' +
                ", userId='" + userId + '\'' +
                ", tokenCreateTime=" + tokenCreateTime +
                ", tokenUpdateTime=" + tokenUpdateTime +
                ", tokenExpireTime=" + tokenExpireTime +
                ", cur_club_id='" + cur_club_id + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Token other = (Token) that;
        return (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
                && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
                && (this.getTokenCreateTime() == null ? other.getTokenCreateTime() == null : this.getTokenCreateTime().equals(other.getTokenCreateTime()))
                && (this.getTokenUpdateTime() == null ? other.getTokenUpdateTime() == null : this.getTokenUpdateTime().equals(other.getTokenUpdateTime()))
                && (this.getTokenExpireTime() == null ? other.getTokenExpireTime() == null : this.getTokenExpireTime().equals(other.getTokenExpireTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTokenCreateTime() == null) ? 0 : getTokenCreateTime().hashCode());
        result = prime * result + ((getTokenUpdateTime() == null) ? 0 : getTokenUpdateTime().hashCode());
        result = prime * result + ((getTokenExpireTime() == null) ? 0 : getTokenExpireTime().hashCode());
        return result;
    }

}