package com.community.dao;
/**
 * @ClassName:
 * @Description: TODO
 * @author linyb3
 * @date
 */

import com.community.model.base.Token;
import com.community.model.base.TokenCriteria;
import org.apache.ibatis.annotations.Param;
import java.util.List;

public interface TokenDAO {
    /*public String getTokenByUserId(@Param("user_id")String userId);
    public String getTokenById(@Param("token_id")String tokenId);
    public String createToken(@Param("user_id")String userId);
    public String updateToken(@Param("token_id")String tokenId);
    public String deleteToken(@Param("token_id")String tokenId);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    long countByExample(TokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int deleteByExample(TokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int insert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int insertSelective(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    List<Token> selectByExample(TokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    Token selectByPrimaryKey(String tokenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Token record, @Param("example") TokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Token record, @Param("example") TokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Token record);
}
